# Run retrieval experiments

Run the configured retrieval models across all datasets and compare the saved metrics.

To add a future variation, register it in `retrieval/factory.py`, add its settings to the config if needed, and add its name to `MODELS` below.

In [3]:
from pathlib import Path
import json
import sys

import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SRC_DIR = PROJECT_ROOT / "src"
SCRIPTS_DIR = PROJECT_ROOT / "scripts"

sys.path.insert(0, str(SRC_DIR))
sys.path.insert(0, str(SCRIPTS_DIR))

from evaluate import main

## Choose models

The names must match entries registered in `RETRIEVER_BUILDERS`.

In [4]:
MODELS = [
    "bm25",
    "dense",
    # "dense_finetuned",
    # "dense_hard_negative",
    # "dense_pseudo_label",
    # "hybrid",
]

## Run experiments

In [5]:
main(models=MODELS)

[INFO] [starting] building docstore

Model:   bm25
Dataset: beir/scifact/test

[INFO] [starting] opening zip file
[INFO] [starting] https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/scifact.zip
docs_iter:   0%|                                      | 0/5183 [00:01<?, ?doc/s]
https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/scifact.zip:

[INFO] [finished] https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/scifact.zip:
docs_iter:   0%|                                      | 0/5183 [00:01<?, ?doc/s]
https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/scifact.zip:
[INFO] [finished] opening zip file [1.19s]
docs_iter: 100%|█████████████████████████| 5183/5183 [00:01<00:00, 3723.28doc/s]
[INFO] [finished] docs_iter: [00:01] [5183doc] [3721.64doc/s]
[INFO] [finished] building docstore [1.41s]
[INFO] Opening /root/.ir_datasets/beir/scifact/docs.pklz4/bin with direct file access
[INFO] [starting] opening zip file
[INFO] [finished] opening zip file [0ms]
[INFO] [starting] opening zip file
[INFO] [finished] opening zip file [0ms]

Documents: 5,183
Queries:   300

Running BM25: 100%|██████████| 300/300 [00:03<00:00, 91.77it/s]
[INFO] [starting] building docstore

bm25 - beir/scifact/test
ndcg@10     : 0.6519
recall@10   : 0.7740
recall@100  : 0.8731
mrr@10      : 0.6186

Model:   bm25
Dataset: beir/fiqa/test

[INFO] [starting] opening zip file
[INFO] If you have a local copy of https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/fiqa.zip, you can symlink it here to avoid downloading it again: /root/.ir_datasets/downloads/17918ed23cd04fb15047f73e6c3bd9d9
[INFO] [starting] https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/fiqa.zip
docs_iter:   0%|                                     | 0/57638 [00:00<?, ?doc/s]
https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/fiqa.zip: 0.0
https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/fiqa.zip: 8.9
https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/fiqa.zip: 31.
https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/fiqa.zip: 53.
https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/fiqa.zip: 75.
[INFO] [finished] https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/fiqa.zip: [00

docs_iter:   0%|                                     | 0/57638 [00:01<?, ?doc/s]
[INFO] [finished] opening zip file [1.63s]
docs_iter: 100%|██████████████████████| 57638/57638 [00:02<00:00, 22021.43doc/s]
[INFO] [finished] docs_iter: [00:02] [57638doc] [22016.08doc/s]
[INFO] [finished] building docstore [2.62s]
[INFO] Opening /root/.ir_datasets/beir/fiqa/docs.pklz4/bin with direct file access
[INFO] [starting] opening zip file
[INFO] [finished] opening zip file [1ms]
[INFO] [starting] opening zip file
[INFO] [finished] opening zip file [0ms]

Documents: 57,638
Queries:   648

Running BM25: 100%|██████████| 648/648 [02:11<00:00,  4.92it/s]
[INFO] [starting] building docstore

bm25 - beir/fiqa/test
ndcg@10     : 0.2167
recall@10   : 0.2780
recall@100  : 0.4737
mrr@10      : 0.2703

Model:   bm25
Dataset: beir/nfcorpus/test

[INFO] [starting] opening zip file
[INFO] [starting] https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/nfcorpus.zip
docs_iter:   0%|                                      | 0/3633 [00:00<?, ?doc/s]
https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/nfcorpus.zip:

[INFO] [finished] https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/nfcorpus.zip:
docs_iter:   0%|                                      | 0/3633 [00:00<?, ?doc/s]
https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/nfcorpus.zip:
[INFO] [finished] opening zip file [300ms]
docs_iter: 100%|█████████████████████████| 3633/3633 [00:00<00:00, 8404.60doc/s]
[INFO] [finished] docs_iter: [00:00] [3633doc] [8392.67doc/s]
[INFO] [finished] building docstore [435ms]
[INFO] Opening /root/.ir_datasets/beir/nfcorpus/docs.pklz4/bin with direct file access
[INFO] [starting] opening zip file
[INFO] [finished] opening zip file [0ms]
[INFO] [starting] opening zip file
[INFO] [finished] opening zip file [0ms]

Documents: 3,633
Queries:   323

Running BM25: 100%|██████████| 323/323 [00:00<00:00, 499.89it/s]
[INFO] Opening /root/.ir_datasets/beir/scifact/docs.pklz4/bin with direct file access

bm25 - beir/nfcorpus/test
ndcg@10     : 0.3071
recall@10   : 0.1521
recall@100  : 0.2356
mrr@10      : 0.5090

Saved bm25 results to: /workspace/robust-dense-retrieval/reports/results/bm25.json

Model:   dense
Dataset: beir/scifact/test
Documents: 5,183
Queries:   300

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/627 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/430 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/81 [00:00<?, ?it/s]

Batches:   0%|          | 0/5 [00:00<?, ?it/s]

dense - beir/scifact/test
ndcg@10     : 0.4870
recall@10   : 0.6393
recall@100  : 0.8342
mrr@10      : 0.4488

Model:   dense
Dataset: beir/fiqa/test

[INFO] Opening /root/.ir_datasets/beir/fiqa/docs.pklz4/bin with direct file access

Documents: 57,638
Queries:   648

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/901 [00:00<?, ?it/s]

Batches:   0%|          | 0/11 [00:00<?, ?it/s]

dense - beir/fiqa/test
ndcg@10     : 0.2317
recall@10   : 0.2945
recall@100  : 0.4956
mrr@10      : 0.2784

Model:   dense
Dataset: beir/nfcorpus/test
Documents: 3,633
Queries:   323

[INFO] Opening /root/.ir_datasets/beir/nfcorpus/docs.pklz4/bin with direct file access

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/57 [00:00<?, ?it/s]

Batches:   0%|          | 0/6 [00:00<?, ?it/s]

dense - beir/nfcorpus/test
ndcg@10     : 0.2597
recall@10   : 0.1123
recall@100  : 0.2341
mrr@10      : 0.4549

Saved dense results to: /workspace/robust-dense-retrieval/reports/results/dense.json

## Compare results

In [6]:
rows = []

for model_name in MODELS:
    result_path = PROJECT_ROOT / "reports" / "results" / f"{model_name}.json"

    with open(result_path) as f:
        result = json.load(f)

    for dataset_name, dataset_result in result["datasets"].items():
        rows.append({
            "model": model_name,
            "dataset": dataset_name,
            **dataset_result["metrics"],
        })

results_df = pd.DataFrame(rows)
results_df

   model             dataset   ndcg@10  recall@10  recall@100    mrr@10
0   bm25   beir/scifact/test  0.651893   0.774000    0.873056  0.618615
1   bm25      beir/fiqa/test  0.216684   0.278013    0.473669  0.270286
2   bm25  beir/nfcorpus/test  0.307054   0.152143    0.235640  0.508971
3  dense   beir/scifact/test  0.487016   0.639333    0.834222  0.448783
4  dense      beir/fiqa/test  0.231684   0.294492    0.495628  0.278382
5  dense  beir/nfcorpus/test  0.259746   0.112271    0.234074  0.454902

## Compact comparison table

In [7]:
results_df.set_index(["model", "dataset"]).round(4)

                          ndcg@10  recall@10  recall@100  mrr@10
model dataset
bm25  beir/scifact/test    0.6519     0.7740      0.8731  0.6186
      beir/fiqa/test       0.2167     0.2780      0.4737  0.2703
      beir/nfcorpus/test   0.3071     0.1521      0.2356  0.5090
dense beir/scifact/test    0.4870     0.6393      0.8342  0.4488
      beir/fiqa/test       0.2317     0.2945      0.4956  0.2784
      beir/nfcorpus/test   0.2597     0.1123      0.2341  0.4549